# ecdsa to send onchain tx
kspath = ""
kspwd = ""

# per chain config
[[multichain]]
chainID = 1
name = "Ethereum mainnet"
# Private gateway endpoint recommended
gateway = "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
BlkDelay = 2
BlkInterval = 12
Brevis = "0x63A825ADD2129410628a8561dDD059646FB49aB0"
BrvEigen = "0x9FC952BdCbB7Daca7d420fA55b942405B073A89d"
BrvRegCo = ""
AVSDir = "0x135dda560e946695d6f155dacafc6f1f25c1f5af"

# must set properly for gw to get old pubkey reg events
MaxBlkDelta = 50000

# gateway only
OpStateRetriever = ""
BlsApkReg = ""
BlsApkStartBlk = 
